services:
  # --- SERVIÇO DO BACKEND (DJANGO) ---
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    
    env_file:
      - ./Backend/.env

    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=meu_banco_dados
      - DB_USER=meu_usuario
      - DB_PASSWORD=minha_senha_forte
    
    depends_on:
      db:
        condition: service_healthy # <-- Espera o DB estar saudável
      
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  # --- SERVIÇO DO FRONTEND (REACT) ---
  frontend:
    build: ./Frontend
    ports:
      - "8080:80"

  # --- SERVIÇO DO BANCO DE DADOS (MYSQL) ---
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: meu_banco_dados
      MYSQL_USER: meu_usuario
      MYSQL_PASSWORD: minha_senha_forte
      MYSQL_ROOT_PASSWORD: minha_senha_root_super_forte
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: